
spring:
  profiles:
    active: localtest

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/debug_trace_dev?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    minIdle: 10
    maxActive: 20

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

log:
  root:
    level: DEBUG