spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/debug_trace_dev?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    minIdle: 10
    maxActive: 20

    jpa:
      show-sql: true

      hibernate:
        ddl-auto: none  # none for production, create or update for localtest

tracedebug:
  moduleId: testmvc
  datasource:
    # 192.168.1.220
    url: jdbc:mysql://127.0.0.1:3306/debug_trace_dev?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    # yqr@2017
    password: 123456
