spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/debug_trace_dev?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    minIdle: 10
    maxActive: 20

    jpa:
      show-sql: true

      hibernate:
        ddl-auto: none  # none for production, create or update for localtest
